server:
  port: 8080

spring:
  application:
    name: swak-demo
  datasource:
    url: jdbc:mysql://localhost:3306/swak_demo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #等待连接池分配连接的最长时间，单位是毫秒
      connection-timeout: 20000
      #连接池中保持的最小空闲连接数
      minimum-idle: 5
      #连接池中最大连接数
      maximum-pool-size: 20
      #连接在池中空闲的最大时间，超过这个时间将被关闭，单位是毫秒
      idle-timeout: 300000
      #连接的最大生命周期，超过这个时间将被关闭，单位是毫秒
      max-lifetime: 2000000
# swak 文档配置
knife4j:
  enable: true
  cors: true
  openapi:
    title: "swak分层"
    concat: "ljq"
    version: "1.0.0"
    group:
      admin:
        groupName: "管理后台"
        api-rule-resources:
          - "com.swak.demo.web.controller"

